### ISSUE TITLE
Lots of errors with this script

### ISSUE THREAD

**Issue by Benjam6** [ajb413/comet-liquidator#1]
I'm getting a long list of errors with this code, mainly undefined errors, in Hardhatconfig, index.ts and sendTranscation.ts.  If anyone can help me out, that would be very much appreciated. Thank you.

**Comment by satyasai69** [comment]
i can help u out bro

**Comment by Benjam6** [comment]
Do you know how to run liquidation scripts? Can yo try running it on your end and let me know if you get the same errors, and possibly how to fix them? Thanks.

**Comment by Benjam6** [comment]
I think I've realized what I may of done wrong. I didn't deploy my own contract to begin with, before running the code. But none the less, if you can help me out, that would be great.

**Comment by zikkuratti** [comment]
Checking for purchasable collateral
There is purchasable collateral
Error: getPoolConfig > no pool config found for 0x3A58a54C066FdC0f2D55FC9C89F0415C92eBf3C4
    at getPoolConfig (C:\Users\zikkuratti\comet-liquidator\scripts\liquidation_bot\liquidateUnderwaterBorrowers.ts:257:11)

**Comment by Benjam6** [comment]
> i can help u out bro

Can I have your email address? I'm still struggling with this

**Comment by zikkuratti** [comment]
i have no this errors check yarn npm node versions
