### ISSUE TITLE
code running error with the mainnet contract

### ISSUE THREAD

**Issue by hdemoraisribeiro** [ajb413/comet-liquidator#3]
Dear Sir,

I am still having problems with the comet-liquidator bot provided by alchemy. I may add the following code run lines for the Alchemy comet-liquidator bot; for the mainnet smart contract  address  0xC70e2915f019e27BAA493972e4627dbc0ED7a794  the following execution information code appears:

Checking 52 addresses [0xE5E548Dbd6A087A24a147890a2d55bd5157e6c6F,0xbD3ABa5983DB94Ae2d079fa393A90fd4D48A6F62,0xb82eE473459EE0628642950a14a22e49b50C9845...]
Attempting to liquidate 0xFEd29d8e6536f90Edb61395F3Be9fa8bb1A9a37D via OnChainLiquidator @0xC70e2915f019e27BAA493972e4627dbc0ED7a794
[simulateTxWithAlchemyApi] {
  changes: [],
  gasUsed: undefined,
  error: { message: 'execution reverted', revertReason: undefined }
}
0x40B38765696e3d5d8d9d834D8AaD4bB6e418E489 {}
Successfully liquidated 0xFEd29d8e6536f90Edb61395F3Be9fa8bb1A9a37D via 0xC70e2915f019e27BAA493972e4627dbc0ED7a794
Attempting to liquidate 0x90dD338A1e89C67b22f580f1725F1a8841058E83 via OnChainLiquidator @0xC70e2915f019e27BAA493972e4627dbc0ED7a794
[simulateTxWithAlchemyApi] {
  changes: [],
  gasUsed: undefined,
  error: { message: 'execution reverted', revertReason: undefined }

I would like to know how to correct the error above from the code.

**Comment by ajb413** [comment]
Error is too vague to make an assessment. Perhaps the account is not liquidatable at the block height in which you ran this.
